# Generated by Django 4.2.4 on 2023-09-05 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booksApp', '0002_alter_book_author_alter_book_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='Books',
        ),
    ]
